CREATE OR REPLACE TABLE COETESTDB.JSON_SCHEMA.EMPLOYEE_JSON (
    JSON_DATA VARIANT
);

CREATE FILE FORMAT JSON_FILE_FORMAT
TYPE = 'JSON'
COMPRESSION = 'AUTO'
ENABLE_OCTAL = FALSE
ALLOW_DUPLICATE = FALSE
STRIP_OUTER_ARRAY = TRUE
STRIP_NULL_VALUES = FALSE
IGNORE_UTF8_ERRORS = FALSE;

CREATE STAGE IF NOT EXISTS JSON_STAGE FILE_FORMAT = JSON_FILE_FORMAT; 


PUT file://C:\json\employee_details.json @JSON_STAGE;

COPY INTO COETESTDB.JSON_SCHEMA.EMPLOYEE_JSON from @json_stage/employee_details.json.gz file_format='JSON_FILE_FORMAT' ON_ERROR​='CONTINUE';

create or replace TABLE COETESTDB.DATAVAULT.HUB_CATEGORY (
	HUB_CATEGORY_KEY VARCHAR(32),
	CATEGORY_NAME VARCHAR(50),
	HUB_LOAD_DT DATE,
	HUB_REC_SRC VARCHAR(10)
);
INSERT INTO COETESTDB.DATAVAULT.HUB_CATEGORY
SELECT         MD5(JSON_DATA: Category::VARCHAR) AS HUB_CATEGORY_KEY, 
               JSON_DATA: Category::VARCHAR AS "Category" ,
               CURRENT_DATE AS HUB_LOAD_DT,  
               'KAGGLE' AS rec_src  
FROM COETESTDB.JSON_SCHEMA.EMPLOYEE_JSON ; 

--Create the SAT Country table
create or replace TABLE COETESTDB.DATAVAULT.SAT_CATEGORY (
	HUB_CATEGORY_KEY VARCHAR(32),
	CATEGORY_NAME VARCHAR(100),
	REGION VARIANT ,
	SAT_LOAD_DT DATE,
	SAT_REC_SRC VARCHAR(10)
);

INSERT INTO COETESTDB.DATAVAULT.SAT_CATEGORY
SELECT         MD5(JSON_DATA: Category::VARCHAR) AS HUB_CATEGORY_KEY, 
               JSON_DATA: Category::VARCHAR AS "Category" ,
               VALUE as Regions,
               CURRENT_DATE AS HUB_LOAD_DT,  
               'KAGGLE' AS rec_src  
FROM COETESTDB.JSON_SCHEMA.EMPLOYEE_JSON ,LATERAL FLATTEN(INPUT => JSON_DATA:Regions); 

select * from COETESTDB.DATAVAULT.HUB_CATEGORY;
select * from COETESTDB.DATAVAULT.SAT_CATEGORY;